# Define the registered checks for the check suite
SilverStripe\ModuleRatings\CheckSuite:
  checks:
    # Each check class is defined with a "points" key indicating the number
    # of points that will be given if the check is successful
    SilverStripe\ModuleRatings\Check\CodeCoverageGoodCheck:
      points: 5
    SilverStripe\ModuleRatings\Check\CodeCoverageGreatCheck:
      points: 5
    SilverStripe\ModuleRatings\Check\CodeOrSrcFolderCheck:
      points: 10
    SilverStripe\ModuleRatings\Check\CodingStandardCheck:
      points: 10
    SilverStripe\ModuleRatings\Check\ContributingFileCheck:
      points: 2
    SilverStripe\ModuleRatings\Check\DocumentationCheck:
      points: 5
    SilverStripe\ModuleRatings\Check\EditorConfigFileCheck:
      points: 5
    SilverStripe\ModuleRatings\Check\GitAttributesFileCheck:
      points: 2
    SilverStripe\ModuleRatings\Check\LicenseCheck:
      points: 5
    SilverStripe\ModuleRatings\Check\ReadmeCheck:
      points: 10
    SilverStripe\ModuleRatings\Check\ScrutinizerCheck:
      points: 10
    SilverStripe\ModuleRatings\Check\TravisCheck:
      points: 20
